server:
  port: 8050
spring:
  application:
    name: "course-enrollment-service"
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import:
      - course-qa.yml
      - course-prod.yml
    profiles:
      active: ${SPRING_PROFILES_ACTIVE:default}
management:
  endpoints:
    web:
      exposure:
        include: "*"

build:
  version: 3.0.0